[network]
port = 30303
discovery = true
nat = "extip:172.20.0.2"

[rpc]
interface = "0.0.0.0"
port = 8545
cors = ["*"]
apis = ["web3", "eth", "personal", "net"]

[account]
password = ["/root/.local/share/openethereum/keys/Proyecto_final/password.pwd"]

[mining]
engine_signer = "0x66942BfBa08A29372eabeB4E992cB7Bdaff0c773"
reseal_on_txs = "all"
min_gas_price = 0
